# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51ab1bdf088348a5b4a0b89a9ed9653d9582fef3d215bd92851b3982cf2ad7537e4d5f7b182b5f190ec034dc568af67f8a7ef1a04a14a215b918ce0f35a71a39

test:
  secret_key_base: d82fde34524b4b5c4bb4ffd8983d7affea942366b684682835482a98a27b1e550aa54849cc51e7c0b6d8db5c55fba83313ddf5ab7ae11e345554cd22b536689a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
